### ISSUE TITLE
UnexpectedRequestError on Linux Mint 17 (Ubuntu 14.04)

### ISSUE THREAD

**Issue by happybob007** [smartsheet-platform/smartsheet-python-sdk#36] opened 2016-01-19 00:02 UTC
Whether I use a valid access token, a revoked token, or "bob", I get the same error:

In [24]: sIn [24]: ss = smartsheet.Smartsheet(new_at)

In [25]: ss.Server.server_info()
/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
##   InsecurePlatformWarning

UnexpectedRequestError                    Traceback (most recent call last)
<ipython-input-25-d0c5d9f86803> in <module>()
----> 1 ss.Server.server_info()

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/server.pyc in server_info(self)
     45         expected = 'ServerInfo'
     46         prepped_request = self._base.prepare_request(_op)
---> 47         response = self._base.request(prepped_request, expected, _op)
     48 
     49         return response

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/smartsheet.pyc in request(self, prepped_request, expected, operation)
    176             The API operation result object.
    177         """
--> 178         res = self.request_with_retry(prepped_request, operation)
    179         native = res.native(expected)
    180 

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/smartsheet.pyc in request_with_retry(self, prepped_request, operation)
    240             self._log.info('Request to %s', prepped_request.url)
    241             try:
--> 242                 return self._request(prepped_request, operation)
    243             except (ApiError, HttpError) as err:
    244                 if isinstance(err, (

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/smartsheet.pyc in _request(self, prepped_request, operation)
    208             res = self._session.send(prepped_request, stream=stream)
    209         except (requests.exceptions.RequestException) as rex:
--> 210             raise UnexpectedRequestError(rex.request, rex.response)
    211 
    212         # req_headers = dump_message_headers(res.request)

UnexpectedRequestError: (<PreparedRequest [GET]>, None)
s = smartsheet.Smartsheet(new_at)

In [25]: ss.Server.server_info()
/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
##   InsecurePlatformWarning

UnexpectedRequestError                    Traceback (most recent call last)
<ipython-input-25-d0c5d9f86803> in <module>()
----> 1 ss.Server.server_info()

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/server.pyc in server_info(self)
     45         expected = 'ServerInfo'
     46         prepped_request = self._base.prepare_request(_op)
---> 47         response = self._base.request(prepped_request, expected, _op)
     48 
     49         return response

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/smartsheet.pyc in request(self, prepped_request, expected, operation)
    176             The API operation result object.
    177         """
--> 178         res = self.request_with_retry(prepped_request, operation)
    179         native = res.native(expected)
    180 

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/smartsheet.pyc in request_with_retry(self, prepped_request, operation)
    240             self._log.info('Request to %s', prepped_request.url)
    241             try:
--> 242                 return self._request(prepped_request, operation)
    243             except (ApiError, HttpError) as err:
    244                 if isinstance(err, (

/home/scottw/code/new-python-sdk/py27/local/lib/python2.7/site-packages/smartsheet/smartsheet.pyc in _request(self, prepped_request, operation)
    208             res = self._session.send(prepped_request, stream=stream)
    209         except (requests.exceptions.RequestException) as rex:
--> 210             raise UnexpectedRequestError(rex.request, rex.response)
    211 
    212         # req_headers = dump_message_headers(res.request)

UnexpectedRequestError: (<PreparedRequest [GET]>, None)

**Comment by happybob007** [comment] 2016-01-19 00:02
The issue with urllib3 is probably at the heart of this.

**Comment by happybob007** [comment] 2016-01-19 00:59
(py27)sc(py27)scottw@hobo ~/code/new-python-sdk $ pip list
argparse (1.2.1)
certifi (2015.11.20.1)
decorator (4.0.6)
ipython (4.0.2)
ipython-genutils (0.1.0)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (1.5.4)
ptyprocess (0.5)
python-dateutil (2.4.2)
requests (2.9.1)
requests-toolbelt (0.5.1)
setuptools (2.2)
simplegeneric (0.8.1)
six (1.10.0)
smartsheet-python-sdk (1.0.1)
traitlets (4.1.0)
wsgiref (0.1.2)
ottw@hobo ~/code/new-python-sdk $ pip list
argparse (1.2.1)
certifi (2015.11.20.1)
decorator (4.0.6)
ipython (4.0.2)
ipython-genutils (0.1.0)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (1.5.4)
ptyprocess (0.5)
python-dateutil (2.4.2)
requests (2.9.1)
requests-toolbelt (0.5.1)
setuptools (2.2)
simplegeneric (0.8.1)
six (1.10.0)
smartsheet-python-sdk (1.0.1)
traitlets (4.1.0)
wsgiref (0.1.2)

**Comment by tberg** [comment] 2016-01-19 18:24
Same issue on Debian 8.0, with Python 2.7.9

````
$ cat apitest.py 
#!/usr/bin/env python
import smartsheet
import smartsheet.sheets
import pprint

client = smartsheet.Smartsheet()
sobj = smartsheet.sheets.Sheets(client)
slist = sobj.list_sheets(include_all=True)
pprint.pprint(slist)
````
````
$ ./apitest.py 
Traceback (most recent call last):
  File "./apitest.py", line 8, in <module>
    slist = sobj.list_sheets(include_all=True)
  File "/usr/local/lib/python2.7/dist-packages/smartsheet/sheets.py", line 662, in list_sheets
    response = self._base.request(prepped_request, expected, _op)
  File "/usr/local/lib/python2.7/dist-packages/smartsheet/smartsheet.py", line 178, in request
    res = self.request_with_retry(prepped_request, operation)
  File "/usr/local/lib/python2.7/dist-packages/smartsheet/smartsheet.py", line 242, in request_with_retry
    return self._request(prepped_request, operation)
  File "/usr/local/lib/python2.7/dist-packages/smartsheet/smartsheet.py", line 210, in _request
    raise UnexpectedRequestError(rex.request, rex.response)
smartsheet.exceptions.UnexpectedRequestError: (<PreparedRequest [GET]>, None)
````
````
$ pip2 list --local
You are using pip version 6.0.6, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
apsw (3.8.6.post1)
apt-xapian-index (0.47)
awscli (1.7.45)
BeautifulSoup (3.2.1)
bicyclerepair (0.9)
boto (2.38.0)
botocore (1.1.8)
Brlapi (0.6.2)
certifi (2015.11.20.1)
cffi (0.8.6)
chardet (2.3.0)
CherryPy (3.5.0)
colorama (0.3.3)
cryptography (0.6.1)
cssselect (0.9.1)
cssutils (0.9.10)
Cython (0.20.2)
decorator (3.4.0)
defer (1.0.6)
defusedxml (0.4.1)
discover (0.4.0)
dm.xmlsec.binding (1.3.2)
dnspython (1.12.0)
docutils (0.12)
feedparser (5.1.3)
flake8 (2.2.4)
Flask (0.10.1)
fpconst (0.7.2)
httplib2 (0.9)
ipaddr (2.1.11)
ipython (2.3.0)
iso8601 (0.1.10)
isodate (0.5.0)
itsdangerous (0.24)
jenkins-job-builder (1.3.0)
jenkinsapi (0.2.25)
Jinja2 (2.7.3)
jmespath (0.7.1)
Kivy (1.8.0)
Kivy-Garden (0.1.1)
lazr.uri (1.0.3)
libvirt-python (1.2.9)
louis (2.5.3)
lxml (3.4.4)
M2Crypto (0.22.3)
Magic-file-extensions (0.2)
Mako (1.0.0)
Markdown (2.5.1)
MarkupSafe (0.23)
mccabe (0.2.1)
mechanize (0.2.5)
mercurial (3.1.2)
mysql-connector-python (1.2.3)
MySQL-python (1.2.5)
ndg-httpsclient (0.3.2)
netifaces (0.10.4)
numpy (1.8.2)
ordereddict (1.1)
pbr (1.8.0)
pep8 (1.5.7)
pexpect (3.2)
Pillow (2.6.1)
pip (6.0.6)
ply (3.4)
py (1.4.26)
pyaml (14.5.7)
pyasn1 (0.1.8)
pychecker (0.8.19)
pycparser (2.10)
pycrypto (2.6.1)
pycups (1.9.63)
pycurl (7.19.5)
pyflakes (0.8.1)
Pygments (2.0.1)
pygobject (3.14.0)
pyliblzma (0.5.3)
pyOpenSSL (0.14)
pyparsing (2.0.3)
pysmbc (1.0.15.3)
pysqlite (1.0.1)
python-apt (0.9.3.11)
python-cjson (1.1.0)
python-dateutil (2.4.2)
python-debian (0.1.23)
python-debianbts (1.11)
python-jenkins (0.4.8)
python-saml (2.1.2)
pytz (2014.7)
pyxdg (0.25)
PyYAML (3.11)
reportbug (6.6.3)
reportlab (3.1.8)
repoze.lru (0.6)
requests (2.4.3)
requests-toolbelt (0.5.1)
roman (2.0.0)
Routes (2.0)
rsa (3.1.4)
setuptools (18.4)
simplegeneric (0.8.1)
six (1.9.0)
smartsheet-python-sdk (1.0.1)
smartsheetclient (0.0.1)
SOAPpy (0.12.22)
Sphinx (1.2.3)
sphinxcontrib-programoutput (0.8)
suds (0.4)
tox (1.8.1)
urlgrabber (3.9.1)
urllib3 (1.9.1)
uTidylib (0.2)
vboxapi (1.0)
virtualenv (1.11.6)
wadllib (1.3.2)
WebOb (1.4)
Werkzeug (0.9.6)
wstools (0.4.3)
wxPython (3.0.1.1)
wxPython-common (3.0.1.1)
yum-metadata-parser (1.1.4)
````

**Comment by kbrandl** [comment] 2016-01-25 18:30
Hi Scott -- can you please try using version 2015.04.28 of certifi, and see if that resolves this issue?

	pip uninstall certifi
	pip install certifi==2015.04.28

**Comment by cmlccie** [comment] 2017-01-27 16:02
@kbrandl  I am receiving receiving the same error on API calls, and using `certifi==2015.04.28` didn't change anything for me.  My scripts were functional before the beginning of the year.  Now all of my calls using the SmartSheet SDK are returning these errors.

## Test Script

``` python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import smartsheet

smartsheet_api = smartsheet.Smartsheet()
smartsheet_user = smartsheet_api.Users.get_current_user()
print "SmartSheet User: %s %s [%s]" % (smartsheet_user.first_name,
                                       smartsheet_user.last_name,
                                       smartsheet_user.email)
```

## Error
``` python
Traceback (most recent call last):
  File "./smartsheet-python-sdk-test.py", line 6, in <module>
    smartsheet_user = smartsheet_api.Users.get_current_user()
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/smartsheet/users.py", line 151, in get_current_user
    response = self._base.request(prepped_request, expected, _op)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 178, in request
    res = self.request_with_retry(prepped_request, operation)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 242, in request_with_retry
    return self._request(prepped_request, operation)
  File "/Users/chrlunsf/dev/envs/dntt-sync/lib/python2.7/site-packages/smartsheet/smartsheet.py", line 210, in _request
    raise UnexpectedRequestError(rex.request, rex.response)
smartsheet.exceptions.UnexpectedRequestError: (<PreparedRequest [GET]>, None)
```

## Installed Packages
``` bash
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2015.4.28)
ciscosparkapi (0.4.2)
future (0.16.0)
pip (9.0.1)
python-dateutil (2.6.0)
requests (2.13.0)
requests-toolbelt (0.7.0)
setuptools (32.3.1)
six (1.10.0)
smartsheet-python-sdk (1.0.1)
wheel (0.30.0a0)
```

**Comment by seweil** [comment] 2017-01-27 18:50
Hi @cmlccie,
We are investigating. 
Your script works on newer versions of certifi - have you tried the latest?

**Comment by cmlccie** [comment] 2017-01-27 20:48
I know the script was functional at least up through October 2016, when its use was suspended, and it was failing when reactivated this month (January 2017).

**Comment by SethGoodLuckMartin** [comment] 2017-02-17 22:51
@cmlccie Could you upgrade your https client with the following command:

`sudo pip install ndg-httpsclient pyasn1 --upgrade
`
That seemed to work for me to get the SDK up and running.

**Comment by joshalbrecht** [comment] 2017-10-16 00:34
I'm getting the same error. I tried all of the suggested fixes here and nothing helped:

```
  File "~/venv/personal/lib/python3.5/site-packages/smartsheet/smartsheet.py", line 242, in _request
    raise HttpError(rex, 'SSL handshake error, old CA bundle or old OpenSSL?')
smartsheet.exceptions.HttpError: (SSLError(MaxRetryError('HTTPSConnectionPool(host=\'api.smartsheet.com\', port=443): Max retries exceeded with url: /2.0/sheets?pageSize=100&includeAll=True&page=1 (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_read_bytes\', \'sslv3 alert handshake failure\')],)",),))',),), 'SSL handshake error, old CA bundle or old OpenSSL?')
```

Installed packages:
```
asana==0.6.2
asn1crypto==0.23.0
attrs==17.2.0
certifi==2017.7.27.1
cffi==1.11.2
chardet==3.0.4
click==6.6
cryptography==2.1.1
decorator==4.0.10
google-api-python-client==1.5.5
httplib2==0.9.2
idna==2.6
ipdb==0.10.1
ipython==5.1.0
ipython-genutils==0.1.0
ndg-httpsclient==0.4.3
oauth2client==4.0.0
oauthlib==2.0.1
pexpect==4.2.1
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.9
ptyprocess==0.5.1
pyasn1==0.3.7
pyasn1-modules==0.0.8
pycparser==2.18
pyfiglet==0.7.5
Pygments==2.1.3
pyOpenSSL==17.3.0
python-dateutil==2.6.1
pytz==2016.10
requests==2.18.4
requests-oauthlib==0.6.2
requests-toolbelt==0.8.0
rsa==3.4.2
sarge==0.1.4
simplegeneric==0.8.1
six==1.11.0
smartsheet-python-sdk==1.2.1
termdown==1.12.0
traitlets==4.3.1
tzlocal==1.3
uritemplate==3.0.0
urllib3==1.22
wcwidth==0.1.7
```

OS: Xubuntu 16.04
Python 3.5.2

This script worked as recently as about 7 days ago (and probably even more recently than that, but I don't remember exactly), and I haven't changed anything about it since then.

**Comment by SethGoodLuckMartin** [comment] 2017-10-16 14:34
Morning @joshalbrecht, another user [on our forum](https://community.smartsheet.com/discussion/python-api-error-ssl-handshake-error-old-ca-bundle-or-old-openssl) seems to have solved by downgrading their requests package as follows:

`pip install requests==2.11.0`

I know that the API team is currently updating the SDKs as well. 
Let me know if that solves the issue for you. Very strange that it just happened unexpectedly like that.

**Comment by seweil** [comment] 2017-10-16 22:49
Hi @joshalbrecht, Are you still encountering the same error? 
On Saturday we disabled TLS 1.0 support.  I'm wondering if that's the root cause of what you observed.

After several reports of errors, it is re-enabled for the time being.

**Comment by joshalbrecht** [comment] 2017-10-22 15:55
It is fixed now, so that likely was the cause.

Thanks!

**Closed** 2020-06-15 23:19 UTC
